FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

ENV NODE_ENV=production
ENV DISCORD_MODE=dm
ENV DISCORD_PREFIX=!nexi

CMD ["npm", "run", "discord"]
